# üè∑Ô∏è **Diabetes Health Indicators** - *Data Preparation & Mapping Script of BRFSS Subset*

## üìä **Description:**

This project prepares and transforms a subset of the 2023 BRFSS dataset focused on diabetes risk factors. It includes code to rename coded variables into readable labels, bin key features like age and income, and clean the dataset for effective analysis and dashboard creation.

## üìÑ **About the Dataset**

This project uses a cleaned and structured subset of the **2023 Behavioral Risk Factor Surveillance System (BRFSS)** survey conducted by the **Centers for Disease Control and Prevention (CDC)**. The BRFSS collects extensive data via telephone interviews from over **400,000 U.S. adults annually** on chronic conditions, lifestyle factors, and access to healthcare.

The selected dataset specifically focuses on **20 features related to diabetes** and its comorbidities (like stroke and heart disease), including behavioral risk factors and social determinants like income and insurance.

*  **Total Responses:** 433,323

*  **Original Dataset Features:** 330+

*  **Selected Subset:** 20 diabetes-related features

*  **Source:** CDC BRFSS 2023

## üìå **Dataset Features Used**

The 20 selected variable columns are categorised into five key categories:

| Category                     | Features                                                                         |
| ---------------------------- | -------------------------------------------------------------------------------- |
| **Health Conditions**        | `DIABETE4`, `DIABTYPE`, `_RFHYPE6`, `_RFCHOL3`, `_CHOLCH3`, `_MICHD`, `CVDSTRK3` |
| **Physical & Mental Health** | `_BMI5`, `PHYSHLTH`, `MENTHLTH`, `DIFFWALK`, `GENHLTH`                           |
| **Behaviors**                | `EXERANY2`, `SMOKE100`                                                           |
| **Access & Coverage**        | `PRIMINS1`, `MEDCOST1`                                                           |
| **Demographics**             | `_AGEG5YR`, `_SEX`, `_EDUCAG`, `_INCOMG1`                                        |

## üßÆ **Codebook Highlights (Sample Value Mappings)**

A few variables and their important mappings based on CDC‚Äôs codebook:

`DIABETE4` ‚Äì **Diabetes Status:**
`1`: Yes | `2`: Yes, Gestational | `3`: No | `4`: Pre-diabetes | `7/9`: Don't Know / Refused | `Blank`: Missing

`_BMI5` ‚Äì **Body Mass Index:**
Values range from 1 to 9999 with two implied decimal places (e.g., 2786 = 27.86)

`CVDSTRK3` ‚Äì **Ever Had a Stroke:**
`1`: Yes | `2`: No | `7/9`: Don't Know / Refused | `Blank`: Missing

`_MICHD` ‚Äì **Had Heart Attack or Coronary Heart Disease:**
`1`: Yes | `2`: No | Blank: Missing

`EXERANY2` ‚Äì **Any Physical Activity in Past 30 Days:**
`1`: Yes | `2`: No | `7/9`: Don‚Äôt Know / Refused | `Blank`: Missing

`PRIMINS1` ‚Äì **Primary Health Coverage:**
`1‚Äì10`: Type of Insurance | `88`: No Coverage | `77/99`: Don‚Äôt Know / Refused

`_AGEG5YR` ‚Äì **Age Group in 5-Year Bins:**
`1`: 18‚Äì24 | ... | `13`: 80+ | `14`: Unknown

`_INCOMG1` ‚Äì **Income Group:**
Ranges from `1`: <15K to `7`: 200K+, with `9`: Unknown

## üîß **Steps Implemented in This Python File**

### **1. Load and Inspect the Data**

Load the CSV file into a Pandas DataFrame


### **2. Clean Column Labels**

Use a dictionary mapping to convert cryptic code-based column names to human-readable labels.

**Example:**

`'DIABETE4' ‚Üí 'Diabetes_Status'`

`'CVDSTRK3' ‚Üí 'Had_Stroke'`

### **3. Replace Categorical Codes with Meaningful Text**

Replaced all numeric codes (like 1, 2, 7, 9) with their corresponding labels.

**Example:**

`1 ‚Üí Yes`

`2 ‚Üí No`

`7/9 ‚Üí Don't Know / Refused`


### **4. Create Binned Ranges for Key Variables**

1. `Age Group`:

  Already binned in _AGEG5YR

2. `Physical Health Days (PHYSHLTH)`:

  Binned into: 1-7 Days, 8‚Äì14 Days, 15‚Äì21 Days, 22‚Äì30 Days

3. `Mental Health Days (MENTHLTH):`

  Binned into: 1-7 Days, 8‚Äì14 Days, 15‚Äì21 Days, 22‚Äì30 Days

4. `Income Group (_INCOMG1)`:

  Grouped into: <25K,  25K‚Äì50K,  50K‚Äì100K,  100K‚Äì200K, >200K+

### **5. Drop Rows with Critical Missing or Refused Values**

*  Removed rows where responses were blank or marked as refused for essential health indicators.

* Viewed the top 50 rows for cleaned analysis.

### **6. Export Cleaned File**

Final cleaned dataset saved as a new .csv naming "Cleaned_Diabetes_Health_Data" and is analyzed in Microsoft Excel.

## üí° **Code Implementation**

In [2]:
# Import pandas for data handling
import pandas as pd

# Load the uploaded CSV file
df = pd.read_csv("/content/Diabetes Health Indicators.csv")

# Preview the first few rows
df.head()

,DIABETE4,DIABTYPE,_RFHYPE6,_RFCHOL3,_CHOLCH3,_BMI5,SMOKE100,CVDSTRK3,_MICHD,EXERANY2,PRIMINS1,MEDCOST1,GENHLTH,MENTHLTH,PHYSHLTH,DIFFWALK,_SEX,_AGEG5YR,_EDUCAG,_INCOMG1
0,1,NaN,2,1.0,1,3047.0,2.0,2,2.0,2,3,2,2,88.0,88.0,1.0,2.0,13.0,3.0,9.0
1,3,NaN,2,2.0,1,2856.0,2.0,2,2.0,1,3,2,2,88.0,88.0,2.0,2.0,13.0,3.0,9.0
2,3,NaN,2,2.0,1,2231.0,1.0,2,2.0,1,3,1,4,2.0,6.0,1.0,2.0,13.0,2.0,1.0
3,3,NaN,1,1.0,1,2744.0,2.0,2,2.0,1,3,2,2,88.0,2.0,1.0,2.0,12.0,3.0,9.0
4,1,NaN,2,1.0,1,2585.0,2.0,2,2.0,1,3,2,4,88.0,88.0,1.0,2.0,12.0,3.0,5.0

In [3]:
# Create mappings to convert numeric codes into human-readable labels

diabete4_map = {
    1: "Yes", 2: "Yes (Gestational)", 3: "No", 4: "Pre-Diabetes/Borderline", 7: "Don't know", 9: "Refused"
}

diabtype_map = {1: "Type 1", 2: "Type 2", 7: "Don't know", 9: "Refused"}
rfhype6_map = {1: "No", 2: "Yes", 9: "Don't know"}
rfchol3_map = {1: "No", 2: "Yes", 9: "Don't know"}
cholch3_map = {1: "Yes in 5 yrs", 2: "No in 5 yrs", 3: "Never checked", 9: "Don't know"}
smoke100_map = {1: "Yes", 2: "No", 7: "Don't know", 9: "Refused"}
cvdstrk3_map = {1: "Yes", 2: "No", 7: "Don't know", 9: "Refused"}
michd_map = {1: "Reported MI/CHD", 2: "Not reported"}
exerany2_map = {1: "Yes", 2: "No", 7: "Don't know", 9: "Refused"}
primins1_map = {1: "Employer/Union", 2: "Private Non-Govt", 3: "Medicare", 4: "Medigap", 5: "Medicaid", 6: "CHIP", 7: "Military TRICARE/VA/CHAMP-VA", 8: "Indian Health Service", 9: "State sponsored Health Plan", 10: "Other Govt Plan", 88: "No coverage of any type", 77: "Don't know", 99: "Refused"}
medcost1_map = {1: "Yes", 2: "No", 7: "Don't know", 9: "Refused"}
genhlth_map = {1: "Excellent", 2: "Very Good", 3: "Good", 4: "Fair", 5: "Poor", 7: "Don't know", 9: "Refused"}
diffwalk_map = {1: "Yes", 2: "No", 7: "Don't know", 9: "Refused"}
sex_map = {1: "Male", 2: "Female"}

ageg5yr_map = {
    1: "18‚Äì24", 2: "25‚Äì29", 3: "30‚Äì34", 4: "35‚Äì39", 5: "40‚Äì44", 6: "45‚Äì49",
    7: "50‚Äì54", 8: "55‚Äì59", 9: "60‚Äì64", 10: "65‚Äì69", 11: "70‚Äì74", 12: "75‚Äì79",
    13: "80+", 14: "Unknown"
}

educag_map = {
    1: "Not Graduated High School", 2: "Graduated High School", 3: "Some College/Tech", 4: "College Grad", 9: "Unknown"
}

incomg1_map = {
    1: "<$15k", 2: "$15k‚Äì$25k", 3: "$25k‚Äì$35k", 4: "$35k‚Äì$50k",
    5: "$50k‚Äì$100k", 6: "$100k‚Äì$200k", 7: "$200k+", 9: "Unknown"
}

In [4]:
#  Add these functions below to the mapping dictionaries

# For BMI
def bmi_category(val):
    try:
        val = float(val)
    except:
        return 'Missing'
    if pd.isnull(val):
        return 'Missing'
    val = val / 100  # Convert to actual BMI
    if val < 18.5:
        return 'Underweight'
    elif val < 25:
        return 'Normal'
    elif val < 30:
        return 'Overweight'
    else:
        return 'Obese'

# For MENTHLTH and PHYSHLTH
def health_days(val):
    try:
        v = int(val)
    except:
        return 'Missing'
    if v == 88:
        return 'None'
    elif v == 77:
        return "Don't know"
    elif v == 99:
        return "Refused"
    elif 1 <= v <= 30:
        return v
    else:
        return 'Missing'

def health_days_bin(val):
    try:
        v = int(val)
    except:
        return 'Missing'
    if v == 88:
        return 'None'
    elif v == 77:
        return "Don't know"
    elif v == 99:
        return "Refused"
    elif 1 <= v <= 7:
        return '1-7 days'
    elif 8 <= v <= 14:
        return '8-14 days'
    elif 15 <= v <= 21:
        return '15-21 days'
    elif 22 <= v <= 30:
        return '22-30 days'
    else:
        return 'Missing'

In [5]:
# Replace code values with their corresponding human-readable labels

df["DIABETE4"] = df["DIABETE4"].map(diabete4_map)
df["DIABTYPE"] = df["DIABTYPE"].map(diabtype_map)
df["_RFHYPE6"] = df["_RFHYPE6"].map(rfhype6_map)
df["_RFCHOL3"] = df["_RFCHOL3"].map(rfchol3_map)
df["_CHOLCH3"] = df["_CHOLCH3"].map(cholch3_map)
df["SMOKE100"] = df["SMOKE100"].map(smoke100_map)
df["CVDSTRK3"] = df["CVDSTRK3"].map(cvdstrk3_map)
df["_MICHD"] = df["_MICHD"].map(michd_map)
df["EXERANY2"] = df["EXERANY2"].map(exerany2_map)
df["PRIMINS1"] = df["PRIMINS1"].map(primins1_map)
df["MEDCOST1"] = df["MEDCOST1"].map(medcost1_map)
df["GENHLTH"] = df["GENHLTH"].map(genhlth_map)
df["DIFFWALK"] = df["DIFFWALK"].map(diffwalk_map)
df["_SEX"] = df["_SEX"].map(sex_map)
df["_AGEG5YR"] = df["_AGEG5YR"].map(ageg5yr_map)
df["_EDUCAG"] = df["_EDUCAG"].map(educag_map)
df["_INCOMG1"] = df["_INCOMG1"].map(incomg1_map)

# For BMI
df['BMI_CAT'] = df['_BMI5'].apply(bmi_category)

# For Mental and Physical Health (days)
df['MENTHLTH_CLEAN'] = df['MENTHLTH'].apply(health_days)
df['PHYSHLTH_CLEAN'] = df['PHYSHLTH'].apply(health_days)

#  For Mental and Physical Health binned ranges:
df['MENTHLTH_BIN'] = df['MENTHLTH'].apply(health_days_bin)
df['PHYSHLTH_BIN'] = df['PHYSHLTH'].apply(health_days_bin)

In [6]:
# Standardize the Age Group
def map_age_group(val):
    if pd.isnull(val):
        return "Don't know/Missing"
    # Standardize: replace en-dash with hyphen, remove spaces, lowercase
    v = str(val).replace('‚Äì', '-').replace('‚Äî', '-').replace(' ', '').lower()
    # Map to 7 groups
    if v in ['18-24', '25-29']:
        return '18-29'
    elif v in ['30-34', '35-39']:
        return '30-39'
    elif v in ['40-44', '45-49']:
        return '40-49'
    elif v in ['50-54', '55-59']:
        return '50-59'
    elif v in ['60-64', '65-69']:
        return '60-69'
    elif v in ['70-74', '75-79', '80+', '80orolder']:
        return '70+'
    elif 'unknown' in v or 'refused' in v or 'missing' in v or 'don\'tknow' in v:
        return "Don't know/Missing"
    else:
        return "Don't know/Missing"

df['AGEGROUP7'] = df['_AGEG5YR'].apply(map_age_group)

In [7]:
age_categories = ["18-29", "30-39", "40-49", "50-59", "60-69", "70+", "Don't know/Missing"]
df['AGEGROUP7'] = pd.Categorical(df['AGEGROUP7'], categories=age_categories, ordered=True)

In [8]:
print(df[['AGEGROUP7', '_AGEG5YR']].head(20))
print(df['AGEGROUP7'].value_counts(dropna=False))

   AGEGROUP7 _AGEG5YR
0        70+      80+
1        70+      80+
2        70+      80+
3        70+    75‚Äì79
4        70+    75‚Äì79
5      60-69    60‚Äì64
6        70+      80+
7        70+    75‚Äì79
8        70+      80+
9        70+    75‚Äì79
10     50-59    55‚Äì59
11       70+    75‚Äì79
12     60-69    65‚Äì69
13       70+    75‚Äì79
14       70+    75‚Äì79
15       70+      80+
16     60-69    60‚Äì64
17       70+      80+
18     60-69    65‚Äì69
19       70+    75‚Äì79
AGEGROUP7
70+                   20246
60-69                 14267
50-59                 10354
30-39                  8533
40-49                  8436
18-29                  7405
Don't know/Missing     1377
Name: count, dtype: int64

In [9]:
# Standardize the Income Group
import re

def map_income_group(val):
    if pd.isnull(val):
        return "Unknown"
    # Standardize string: lowercase, remove $, spaces, commas, replace all dashes with hyphen
    v = str(val).lower().replace('$', '').replace(',', '').replace(' ', '')
    v = v.replace('‚Äì', '-').replace('‚Äî', '-')
    # Use regex to match ranges and single values
    if re.match(r'^<*1[5-9]k$', v) or v in ['<15k', '15k-25k']:
        return "<$25K"
    elif v in ['15k-25k', '25k-35k', '35k-50k'] or re.match(r'^1[5-9]k-2[5-9]k$', v) or re.match(r'^2[5-9]k-3[5-9]k$', v) or re.match(r'^3[5-9]k-5[0-9]k$', v):
        # Merge all 15k-25k, 25k-35k, 35k-50k into correct groups
        if v in ['15k-25k']:
            return "<$25K"
        else:
            return "$25K‚Äì<$50K"
    elif v in ['50k-100k']:
        return "$50K‚Äì<$100K"
    elif v in ['100k-200k']:
        return "$100K‚Äì<$200K"
    elif v in ['200k+', '200korover', '200kormore']:
        return "$200K+"
    elif 'unknown' in v or 'refus' in v or 'miss' in v or 'not sure' in v:
        return "Unknown"
    else:
        # For any other variants, try to parse the numbers
        if re.match(r'^\d+k-\d+k$', v):
            low, high = [int(x.replace('k','')) for x in v.split('-')]
            if high <= 25:
                return "<$25K"
            elif 25 <= low < 50:
                return "$25K‚Äì<$50K"
            elif 50 <= low < 100:
                return "$50K‚Äì<$100K"
            elif 100 <= low < 200:
                return "$100K‚Äì<$200K"
            elif low >= 200:
                return "$200K+"
        return "Unknown"

In [10]:
df['INCOME_GROUPED'] = df['_INCOMG1'].apply(map_income_group)

In [11]:
income_categories = ["<$25K", "$25K‚Äì<$50K", "$50K‚Äì<$100K", "$100K‚Äì<$200K", "$200K+", "Unknown"]
df['INCOME_GROUPED'] = pd.Categorical(df['INCOME_GROUPED'], categories=income_categories, ordered=True)

In [12]:
# View top 50 rows of cleaned data
df.head(50)

,DIABETE4,DIABTYPE,_RFHYPE6,_RFCHOL3,_CHOLCH3,_BMI5,SMOKE100,CVDSTRK3,_MICHD,EXERANY2,...,_AGEG5YR,_EDUCAG,_INCOMG1,BMI_CAT,MENTHLTH_CLEAN,PHYSHLTH_CLEAN,MENTHLTH_BIN,PHYSHLTH_BIN,AGEGROUP7,INCOME_GROUPED
0,Yes,NaN,Yes,No,Yes in 5 yrs,3047.0,No,No,Not reported,No,...,80+,Some College/Tech,Unknown,Obese,None,None,None,None,70+,Unknown
1,No,NaN,Yes,Yes,Yes in 5 yrs,2856.0,No,No,Not reported,Yes,...,80+,Some College/Tech,Unknown,Overweight,None,None,None,None,70+,Unknown
2,No,NaN,Yes,Yes,Yes in 5 yrs,2231.0,Yes,No,Not reported,Yes,...,80+,Graduated High School,<$15k,Normal,2,6,1-7 days,1-7 days,70+,<$25K
3,No,NaN,No,No,Yes in 5 yrs,2744.0,No,No,Not reported,Yes,...,75‚Äì79,Some College/Tech,Unknown,Overweight,None,2,None,1-7 days,70+,Unknown
4,Yes,NaN,Yes,No,Yes in 5 yrs,2585.0,No,No,Not reported,Yes,...,75‚Äì79,Some College/Tech,$50k‚Äì$100k,Overweight,None,None,None,None,70+,$50K‚Äì<$100K
5,No,NaN,Yes,Yes,Yes in 5 yrs,3018.0,No,No,Not reported,Yes,...,60‚Äì64,Some College/Tech,$50k‚Äì$100k,Obese,3,2,1-7 days,1-7 days,60-69,$50K‚Äì<$100K
6,No,NaN,No,No,Yes in 5 yrs,2441.0,Yes,No,Not reported,No,...,80+,Graduated High School,$35k‚Äì$50k,Normal,Don't know,8,Don't know,8-14 days,70+,$25K‚Äì<$50K
7,Yes,NaN,Yes,Yes,Yes in 5 yrs,2727.0,No,No,Not reported,No,...,75‚Äì79,Some College/Tech,Unknown,Overweight,None,1,None,1-7 days,70+,Unknown
8,No,NaN,Yes,Yes,Yes in 5 yrs,3347.0,No,No,Not reported,No,...,80+,Some College/Tech,$35k‚Äì$50k,Obese,None,5,None,1-7 days,70+,$25K‚Äì<$50K
9,Yes,NaN,Yes,Yes,Yes in 5 yrs,2296.0,Yes,No,Reported MI/CHD,Yes,...,75‚Äì79,Graduated High School,$50k‚Äì$100k,Normal,None,None,None,None,70+,$50K‚Äì<$100K
10,No,NaN,Yes,Yes,Yes in 5 yrs,4184.0,No,No,Not reported,Yes,...,55‚Äì59,Some College/Tech,$50k‚Äì$100k,Obese,None,None,None,None,50-59,$50K‚Äì<$100K
11,No,NaN,Yes,Yes,Yes in 5 yrs,2413.0,No,No,Not reported,No,...,75‚Äì79,Graduated High School,Unknown,Normal,None,2,None,1-7 days,70+,Unknown
12,No,NaN,No,No,Yes in 5 yrs,2965.0,Yes,No,Not reported,Yes,...,65‚Äì69,College Grad,$100k‚Äì$200k,Overweight,None,None,None,None,60-69,$100K‚Äì<$200K
13,No,NaN,No,No,Yes in 5 yrs,2375.0,Yes,No,Not reported,No,...,75‚Äì79,Some College/Tech,$100k‚Äì$200k,Normal,None,None,None,None,70+,$100K‚Äì<$200K
14,No,NaN,Yes,No,Yes in 5 yrs,2597.0,Yes,No,Not reported,No,...,75‚Äì79,Some College/Tech,$100k‚Äì$200k,Overweight,None,None,None,None,70+,$100K‚Äì<$200K
15,No,NaN,Yes,No,Yes in 5 yrs,2819.0,No,No,Not reported,Yes,...,80+,Graduated High School,$15k‚Äì$25k,Overweight,None,4,None,1-7 days,70+,<$25K
16,No,NaN,Yes,No,Yes in 5 yrs,3599.0,No,No,Not reported,Don't know,...,60‚Äì64,College Grad,Unknown,Obese,10,30,8-14 days,22-30 days,60-69,Unknown
17,No,NaN,Yes,No,Yes in 5 yrs,2697.0,No,No,Not reported,No,...,80+,College Grad,Unknown,Overweight,None,15,None,15-21 days,70+,Unknown
18,No,NaN,Yes,No,Yes in 5 yrs,2929.0,Yes,Yes,Not reported,No,...,65‚Äì69,Some College/Tech,$25k‚Äì$35k,Overweight,25,None,22-30 days,None,60-69,$25K‚Äì<$50K
19,Yes,NaN,Yes,Yes,Yes in 5 yrs,2741.0,Yes,No,Not reported,Yes,...,75‚Äì79,Graduated High School,$35k‚Äì$50k,Overweight,None,None,None,None,70+,$25K‚Äì<$50K
20,Yes,NaN,Yes,No,Yes in 5 yrs,3605.0,Yes,No,Not reported,Yes,...,80+,Graduated High School,$25k‚Äì$35k,Obese,None,5,None,1-7 days,70+,$25K‚Äì<$50K
21,No,NaN,Yes,Yes,Yes in 5 yrs,2500.0,No,No,Reported MI/CHD,Yes,...,80+,Graduated High School,$15k‚Äì$25k,Overweight,None,None,None,None,70+,<$25K
22,No,NaN,Yes,Yes,Yes in 5 yrs,2424.0,No,No,Reported MI/CHD,Yes,...,80+,Some College/Tech,Unknown,Normal,None,None,None,None,70+,Unknown
23,No,NaN,Yes,Yes,Yes in 5 yrs,NaN,NaN,No,Reported MI/CHD,Yes,...,70‚Äì74,Not Graduated High School,<$15k,Missing,None,None,None,None,70+,<$25K
24,Yes,NaN,Yes,Yes,Yes in 5 yrs,2663.0,No,No,Reported MI/CHD,Yes,...,70‚Äì74,Some College/Tech,$35k‚Äì$50k,Overweight,None,None,None,None,70+,$25K‚Äì<$50K
25,Yes,NaN,No,Yes,Yes in 5 yrs,NaN,No,No,Not reported,No,...,80+,College Grad,Unknown,Missing,None,15,None,15-21 days,70+,Unknown
26,No,NaN,Yes,No,Yes in 5 yrs,2226.0,No,No,Not reported,No,...,80+,Some College/Tech,Unknown,Normal,10,2,8-14 days,1-7 days,70+,Unknown
27,No,NaN,Yes,No,Yes in 5 yrs,NaN,NaN,No,Not reported,No,...,80+,Some College/Tech,Unknown,Missing,None,None,None,None,70+,Unknown
28,Yes,NaN,Yes,Yes,Yes in 5 yrs,3260.0,No,No,Not reported,No,...,65‚Äì69,Graduated High School,Unknown,Obese,None,30,None,22-30 days,60-69,Unknown
29,Yes,NaN,Yes,Yes,Yes in 5 yrs,2496.0,No,No,Not reported,No,...,70‚Äì74,Some College/Tech,$35k‚Äì$50k,Normal,None,21,None,15-21 days,70+,$25K‚Äì<$50K
30,No,NaN,Yes,Yes,Yes in 5 yrs,3013.0,Yes,No,Not reported,Yes,...,70‚Äì74,Some College/Tech,$50k‚Äì$100k,Obese,None,None,None,None,70+,$50K‚Äì<$100K
31,No,NaN,Yes,Yes,Yes in 5 yrs,3779.0,No,Yes,Not reported,No,...,65‚Äì69,College Grad,$50k‚Äì$100k,Obese,None,None,None,None,60-69,$50K‚Äì<$100K
32,Yes,NaN,Yes,Yes,Yes in 5 yrs,4439.0,Yes,No,Not reported,Yes,...,55‚Äì59,College Grad,$25k‚Äì$35k,Obese,None,None,None,None,50-59,$25K‚Äì<$50K
33,No,NaN,Yes,No,Yes in 5 yrs,2480.0,Yes,No,Not reported,Yes,...,65‚Äì69,Graduated High School,Unknown,Normal,None,None,None,None,60-69,Unknown
34,No,NaN,Yes,No,Yes in 5 yrs,3662.0,No,No,Not reported,Yes,...,75‚Äì79,Some College/Tech,Unknown,Obese,None,None,None,None,70+,Unknown
35,No,NaN,Yes,Yes,Yes in 5 yrs,2912.0,Yes,No,Not reported,Yes,...,80+,Graduated High School,$25k‚Äì$35k,Overweight,None,5,None,1-7 days,70+,$25K‚Äì<$50K
36,Yes,NaN,Yes,No,Yes in 5 yrs,3776.0,Yes,No,Not reported,No,...,70‚Äì74,Graduated High School,$15k‚Äì$25k,Obese,10,None,8-14 days,None,70+,<$25K
37,No,NaN,Yes,Yes,Yes in 5 yrs,2626.0,No,Yes,Not reported,No,...,80+,Graduated High School,<$15k,Overweight,None,2,None,1-7 days,70+,<$25K
38,No,NaN,Yes,Yes,Yes in 5 yrs,3095.0,No,No,Reported MI/CHD,Yes,...,70‚Äì74,Some College/Tech,$35k‚Äì$50k,Obese,3,10,1-7 days,8-14 days,70+,$25K‚Äì<$50K
39,No,NaN,Yes,Yes,Yes in 5 yrs,2584.0,No,No,Not reported,No,...,75‚Äì79,Not Graduated High School,Unknown,Overweight,None,None,None,None,70+,Unknown
40,No,NaN,No,Yes,Yes in 5 yrs,2439.0,Yes,No,Reported MI/CHD,No,...,80+,College Grad,$15k‚Äì$25k,Normal,None,None,None,None,70+,<$25K
41,No,NaN,Yes,Yes,Yes in 5 yrs,2373.0,Yes,No,Not reported,Yes,...,65‚Äì69,College Grad,$200k+,Normal,None,None,None,None,60-69,$200K+
42,Yes,NaN,Yes,NaN,Never checked,3347.0,Yes,No,Not reported,Yes,...,75‚Äì79,Not Graduated High School,$25k‚Äì$35k,Obese,None,None,None,None,70+,$25K‚Äì<$50K
43,No,NaN,Yes,Yes,Yes in 5 yrs,3071.0,No,No,Not reported,No,...,70‚Äì74,Not Graduated High School,$15k‚Äì$25k,Obese,None,5,None,1-7 days,70+,<$25K
44,No,NaN,No,No,Yes in 5 yrs,2583.0,Yes,No,Not reported,No,...,80+,College Grad,$100k‚Äì$200k,Overweight,None,None,None,None,70+,$100K‚Äì<$200K
45,Yes,NaN,Yes,Yes,Yes in 5 yrs,2865.0,Yes,No,Not reported,No,...,70‚Äì74,Graduated High School,$50k‚Äì$100k,Overweight,None,None,None,None,70+,$50K‚Äì<$100K
46,No,NaN,No,No,Yes in 5 yrs,2506.0,No,No,Not reported,Yes,...,45‚Äì49,College Grad,$100k‚Äì$200k,Overweight,3,25,1-7 days,22-30 days,40-49,$100K‚Äì<$200K
47,No,NaN,Yes,Yes,Yes in 5 yrs,2695.0,No,No,Not reported,Yes,...,80+,Graduated High School,Unknown,Overweight,None,14,None,8-14 days,70+,Unknown
48,No,NaN,Yes,No,Yes in 5 yrs,NaN,Yes,No,Not reported,Yes,...,70‚Äì74,Some College/Tech,$35k‚Äì$50k,Missing,5,None,1-7 days,None,70+,$25K‚Äì<$50K
49,Yes,NaN,No,Yes,Yes in 5 yrs,2427.0,Yes,No,Reported MI/CHD,No,...,60‚Äì64,Graduated High School,$100k‚Äì$200k,Normal,30,None,22-30 days,None,60-69,$100K‚Äì<$200K

In [13]:
# Save the cleaned file as CSV
df.to_csv("Cleaned_Diabetes_Health_Data.csv", index=False)

# Download to your system
from google.colab import files
files.download("Cleaned_Diabetes_Health_Data.csv")